"""
BankCore — Day 13: Database Schema
=====================================
SQLite schema for BankCore.

Design decisions documented in docs/jour-13/README.md:
  - Transactions are append-only (never updated or deleted)
  - balance_after stored on each transaction (intentional denormalization)
  - Transfer is a separate entity linking two transactions
  - UUID primary keys (generated by domain, not database)
  - CHECK constraints enforce business rules at the database level

This module provides:
  - SCHEMA_SQL: the full DDL as a string (for testing and inspection)
  - create_schema(): creates all tables and indexes in a connection
  - BankSchema: context manager for schema management
"""

import sqlite3
from contextlib import contextmanager
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# Schema DDL
# ---------------------------------------------------------------------------

SCHEMA_SQL = """
-- ============================================================
-- BankCore Database Schema
-- Day 13: Database Modelling
-- ============================================================

PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;

-- ------------------------------------------------------------
-- Owner: a person who can hold multiple accounts
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS owner (
    owner_id    TEXT PRIMARY KEY,
    full_name   TEXT NOT NULL,
    email       TEXT UNIQUE,
    phone       TEXT,
    created_at  TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ------------------------------------------------------------
-- Account: a bank account owned by one owner
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS account (
    account_id           TEXT PRIMARY KEY,
    owner_id             TEXT NOT NULL REFERENCES owner(owner_id),
    account_type         TEXT NOT NULL CHECK (account_type IN ('current', 'savings', 'pro', 'youth')),
    balance              REAL NOT NULL DEFAULT 0.0,
    min_possible_balance REAL NOT NULL DEFAULT 0.0,
    status               TEXT NOT NULL DEFAULT 'ACTIVE'
                             CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED')),
    created_at           TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at           TEXT NOT NULL DEFAULT (datetime('now')),

    -- Database-level enforcement of the LSP invariant (Day 08)
    CHECK (balance >= min_possible_balance)
);

-- ------------------------------------------------------------
-- Transaction: every debit or credit (append-only)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "transaction" (
    tx_id         TEXT PRIMARY KEY,
    account_id    TEXT NOT NULL REFERENCES account(account_id),
    amount        REAL NOT NULL CHECK (amount != 0),
    balance_after REAL NOT NULL,
    description   TEXT NOT NULL DEFAULT '',
    tx_type       TEXT NOT NULL CHECK (tx_type IN (
                      'DEPOSIT', 'WITHDRAWAL', 'TRANSFER_DEBIT',
                      'TRANSFER_CREDIT', 'FEE', 'INTEREST',
                      'REVERSAL', 'OPENING'
                  )),
    created_at    TEXT NOT NULL DEFAULT (datetime('now')),

    -- Immutability: no UPDATE trigger enforced at application level
    -- (see SchemaValidator for verification)
    CONSTRAINT tx_amount_direction CHECK (
        (tx_type IN ('DEPOSIT', 'TRANSFER_CREDIT', 'INTEREST') AND amount > 0)
        OR
        (tx_type IN ('WITHDRAWAL', 'TRANSFER_DEBIT', 'FEE') AND amount < 0)
        OR
        (tx_type IN ('REVERSAL', 'OPENING'))  -- can be either direction
    )
);

-- ------------------------------------------------------------
-- Transfer: links a debit transaction to a credit transaction
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS transfer (
    transfer_id  TEXT PRIMARY KEY,
    debit_tx_id  TEXT NOT NULL REFERENCES "transaction"(tx_id),
    credit_tx_id TEXT REFERENCES "transaction"(tx_id),  -- nullable: credit may be pending
    amount       REAL NOT NULL CHECK (amount > 0),
    status       TEXT NOT NULL DEFAULT 'PENDING'
                     CHECK (status IN ('PENDING', 'COMPLETED', 'REVERSED', 'FAILED')),
    initiated_by TEXT NOT NULL DEFAULT 'system',
    description  TEXT NOT NULL DEFAULT '',
    created_at   TEXT NOT NULL DEFAULT (datetime('now')),
    completed_at TEXT,

    CONSTRAINT transfer_debit_credit_different CHECK (debit_tx_id != credit_tx_id)
);

-- ------------------------------------------------------------
-- FeeRecord: audit trail for every fee deducted
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fee_record (
    fee_id        TEXT PRIMARY KEY,
    account_id    TEXT NOT NULL REFERENCES account(account_id),
    linked_tx_id  TEXT REFERENCES "transaction"(tx_id),
    fee_amount    REAL NOT NULL CHECK (fee_amount >= 0),
    strategy_name TEXT NOT NULL DEFAULT 'StandardFeeStrategy',
    operation     TEXT NOT NULL DEFAULT 'transfer',
    created_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

-- ------------------------------------------------------------
-- Indexes: optimized for the most common query patterns
-- ------------------------------------------------------------

-- Fetch account history (most frequent query)
CREATE INDEX IF NOT EXISTS idx_tx_account_id
    ON "transaction"(account_id);

CREATE INDEX IF NOT EXISTS idx_tx_account_time
    ON "transaction"(account_id, created_at DESC);

-- Find accounts by owner
CREATE INDEX IF NOT EXISTS idx_account_owner_id
    ON account(owner_id);

-- Filter active accounts
CREATE INDEX IF NOT EXISTS idx_account_status
    ON account(status);

-- Audit: transfers by date range
CREATE INDEX IF NOT EXISTS idx_transfer_created_at
    ON transfer(created_at DESC);

-- Fee reporting by account
CREATE INDEX IF NOT EXISTS idx_fee_account_id
    ON fee_record(account_id);
"""

# ---------------------------------------------------------------------------
# Schema creation utilities
# ---------------------------------------------------------------------------

def create_schema(conn: sqlite3.Connection) -> None:
    """
    Execute the full schema DDL on the given connection.
    Idempotent: uses IF NOT EXISTS on all CREATE statements.
    """
    conn.executescript(SCHEMA_SQL)
    conn.commit()


def get_connection(db_path: str = ":memory:") -> sqlite3.Connection:
    """
    Open a SQLite connection with BankCore settings.
    Defaults to in-memory database for testing.
    """
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row   # dict-like row access
    conn.execute("PRAGMA foreign_keys = ON")
    conn.execute("PRAGMA journal_mode = WAL")
    return conn


@contextmanager
def schema_connection(db_path: str = ":memory:"):
    """
    Context manager: open a connection, create schema, yield, close.

    Usage:
        with schema_connection() as conn:
            conn.execute("INSERT INTO owner ...")
    """
    conn = get_connection(db_path)
    try:
        create_schema(conn)
        yield conn
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# Schema introspection helpers
# ---------------------------------------------------------------------------

class SchemaInspector:
    """
    Query SQLite metadata to verify schema structure.
    Used in tests and migrations.
    """

    def __init__(self, conn: sqlite3.Connection) -> None:
        self._conn = conn

    def tables(self) -> list[str]:
        """Return all table names in the database."""
        rows = self._conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
        ).fetchall()
        return [r["name"] for r in rows]

    def columns(self, table: str) -> list[dict]:
        """Return column info for a table."""
        # Quote the table name to handle reserved words like "transaction"
        rows = self._conn.execute(f'PRAGMA table_info("{table}")').fetchall()
        return [dict(r) for r in rows]

    def column_names(self, table: str) -> list[str]:
        return [c["name"] for c in self.columns(table)]

    def indexes(self, table: str) -> list[str]:
        """Return index names for a table."""
        rows = self._conn.execute(
            "SELECT name FROM sqlite_master WHERE type='index' AND tbl_name=?",
            (table,)
        ).fetchall()
        return [r["name"] for r in rows]

    def foreign_keys(self, table: str) -> list[dict]:
        """Return foreign key constraints for a table."""
        rows = self._conn.execute(f'PRAGMA foreign_key_list("{table}")').fetchall()
        return [dict(r) for r in rows]

    def has_table(self, table: str) -> bool:
        return table in self.tables()

    def has_column(self, table: str, column: str) -> bool:
        return column in self.column_names(table)

    def has_index(self, index_name: str) -> bool:
        all_indexes = self._conn.execute(
            "SELECT name FROM sqlite_master WHERE type='index'"
        ).fetchall()
        return index_name in [r["name"] for r in all_indexes]
